services:
    postgres:
        image: postgres:15
        container_name: iragifts-postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data

    redis:
        image: redis/redis-stack:latest
        container_name: iragifts-redis
        restart: unless-stopped
        ports:
            - 6379:6379
            - 8082:8001
        volumes:
            - ./.data/redis:/data

    meilisearch:
        image: getmeili/meilisearch:v1.12.7
        container_name: iragifts-meilisearch
        restart: unless-stopped
        ports:
            - 7700:7700
        volumes:
            - ./.data/meili_data:/meili_data
        environment:
            MEILI_MASTER_KEY: MASTER_KEY

    pgadmin:
        image: dpage/pgadmin4
        container_name: iragifts-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 8080:80
        volumes:
            - ./.data/pg_admin:/var/lib/pgadmin
        depends_on:
            - postgres

    adminer:
        image: adminer
        container_name: iragifts-adminer
        restart: unless-stopped
        ports:
            - 8081:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres

    medusa:
        container_name: iragifts-store
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000"
        env_file:
            - .env.docker
        depends_on:
            - postgres
            - redis
            - meilisearch
